// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bogolang_payload.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *LoginRequest) Validate() error {
	return nil
}
func (this *LoginResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *DataLogin) Validate() error {
	return nil
}
func (this *GetAllUserResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetAllUserRequest) Validate() error {
	return nil
}
func (this *UserData) Validate() error {
	if this.LastAccess != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LastAccess); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LastAccess", err)
		}
	}
	return nil
}
func (this *CreateUserRequest) Validate() error {
	return nil
}
func (this *CreateUserResponse) Validate() error {
	return nil
}
func (this *UpdateUserRequest) Validate() error {
	return nil
}
func (this *UpdateUserResponse) Validate() error {
	return nil
}
func (this *DeleteUserRequest) Validate() error {
	return nil
}
func (this *DeleteUserResponse) Validate() error {
	return nil
}
